### ISSUE TITLE
Node v12 Compatibility

### ISSUE THREAD

**Issue by privatenumber** [jaredwray/keyv-memcache#8]
Hey, thanks for making this package!

I'm using the latest Node LTS (`v12.14.0`) with npm config `engine-strict=true`, and I'm getting an error on installation due to [`package.engines`](https://github.com/jaredwray/keyv-memcache/blob/master/package.json#L12) specifying a v10 range.

```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for keyv-memcache@0.8.0: wanted: {"node":"^10.16.0"} (current: {"node":"12.14.0","npm":"6.13.4"})
npm ERR! notsup Not compatible with your version of node/npm: keyv-memcache@0.8.0
npm ERR! notsup Not compatible with your version of node/npm: keyv-memcache@0.8.0
npm ERR! notsup Required: {"node":"^10.16.0"}
npm ERR! notsup Actual:   {"npm":"6.13.4","node":"12.14.0"}
```

Could the engine property be updated to a floor? `>10.16.0`

**Comment by vied12** [comment]
Hi,

I made a PR that should fix your issue https://github.com/jaredwray/keyv-memcache/pull/9

**Comment by rijkvanzanten** [comment]
This is fixed in https://github.com/jaredwray/keyv-memcache/pull/9

**Comment by privatenumber** [comment]
Nice, thanks!

When is the release planned?

**Comment by rijkvanzanten** [comment]
I personally have no idea (I'm not a maintainer of this project 👀)

Sorry to bother you again, but could you push it up to NPM when you have a second @jaredwray?

**Comment by jaredwray** [comment]
https://www.npmjs.com/package/keyv-memcache 

Done 🥇
